services:
  - type: web
    name: racheal-lendsqr-be-test
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/v1/health
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: ADJUTOR_API_URL
        value: https://adjutor.lendsqr.com/v2
      - key: ADJUTOR_API_KEY
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
